platform :ios, '9.0'
target 'GG_iOSProject' do
inhibit_all_warnings!

# 网络请求
pod 'AFNetworking'
pod 'ASIHTTPRequest'
# 网络监控
pod 'Reachability'

#字典转模型
pod 'MJExtension'
# 下拉刷新
pod 'MJRefresh'
# 图片加载
pod 'SDWebImage'
#用于适配
pod 'Masonry'

#友盟统计和分享
# 基础库
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
#统计 SDK
pod 'UMCAnalytics'
#Push SDK
pod 'UMCPush'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMCShare/UI'
# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
pod 'UMCShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
pod 'UMCShare/Social/ReducedSina'


#百度地图SDK
pod 'BaiduMapKit'

# 环信聊天包含实时语音版本
# pod 'Hyphenate'
# pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

pod 'CYLTabBarController'

# 表情键盘
pod 'HMEmoticon'
# 正则匹配点击
pod 'KILabel'


# YYKit
#pod 'YYKit'
pod 'YYImage'
pod 'YYText'
pod 'YYAsyncLayer'
pod 'YYCategories'

# 通用链接跳转
pod 'MagicWindowSDK'

# 数据库 新浪微博用
pod 'FMDB'

# 蒙版
pod 'MBProgressHUD'

# h5交互
pod 'WebViewJavascriptBridge'

# 进度
pod 'M13ProgressSuite'

# 无线轮播
pod 'SDCycleScrollView'

# 键盘管理
pod 'IQKeyboardManager'

# 唯一设备标识
pod 'FCUUID'

# 指纹识别
#pod 'TDTouchID'

# 三级联动 时间 地址
pod 'MOFSPickerManager'


# 全局滑动
pod 'FDFullscreenPopGesture'

# toast
pod 'Toast'

# 二维码
pod 'HMQRCodeScanner'

# 照片
pod 'TZImagePickerController'

# 动态 collectionView
pod 'LxGridView'

# 脸部识别
pod 'iflyMSC'

# scrollpageView
pod 'ZJScrollPageView'

# 列表视频
pod 'ZFPlayer'
pod 'ZFDownload'

# mark- 好玩的
# 泡泡uibutton
pod 'DWBubbleMenuButton'

end
